apiVersion: v1
kind: Service
metadata:
  name: namenode
  labels:
      app: namenode
spec:
  ports:
  - port: 9000
    name: hdfs
  clusterIP: None
  selector:
    app: namenode
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-ui
  labels:
    app: namenode
spec:
  selector:
    app: namenode
  ports:
  - name: hdfs-ui
    port: 9870
    targetPort: 9870
    protocol: TCP
  type: LoadBalancer