apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
  namespace: hdfs
  labels:
    component: hdfs
    role: namenode
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    component: hdfs
    role: namenode