apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: hdfs-cluster
  name: namenode-storage-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 201Gi
  storageClassName: fast