apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-namenode
  labels:
    app: namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
      - name: namenode
        imagePullPolicy: Always
        args:
        - "-c"
        - "cp /tmp/*-site.xml $HADOOP_HOME/etc/hadoop/ && hdfs namenode"
        command: 
        - "/bin/bash"
        image: akhilkm/hdfs:v1
        ports:
        - containerPort: 9000
          name: hdfs
        - containerPort: 9870
          name: hdfs-ui
        volumeMounts:
        - name: core-site
          mountPath: /tmp/core-site.xml
          subPath: core-site.xml
        - name: hdfs-site
          mountPath: /tmp/hdfs-site.xml
          subPath: hdfs-site.xml
      volumes:
        - name: core-site
          configMap:
            name: core-site
        - name: hdfs-site
          configMap:
            name: hdfs-site