apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-namenode
  labels:
    app: namenode
spec:
  replicas: 3
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
      - name: namenode
        image: akhilkm/hdfs:v1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: core-site
          mountPath: /opt/hadoop/etc/hadoop/core-site.xml
          subPath: core-site.xml
        - name: hdfs-site
          mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
          subPath: hdfs-site.xml
        - name: workers
          mountPath: /opt/hadoop/etc/hadoop/workers
          subPath: workers
  volumes:
    - name: core-site
      configMap:
        name: core-site
  volumes:
    - name: hdfs-site
      configMap:
        name: hdfs-site
  volumes:
    - name: workers
      configMap:
        name: workers