# Base image UBUNTU-16.04

FROM ubuntu:16.04

MAINTAINER DevOps <akhilu011@gmail.com>

# Default to UTF-8 file.encoding
ENV LANG C.UTF-8

RUN apt-get update -y \
    && apt-get install -y openjdk-8-jdk wget openssh-server net-tools curl vim

# RUN curl -O https://dist.apache.org/repos/dist/release/hadoop/common/KEYS

# Set environment veriables
ENV HADOOP_VERSION 3.2.1
ENV HADOOP_URL https://www.apache.org/dist/hadoop/common/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz
ENV HADOOP_HOME /home/hadoop/hadoop
ENV PATH ${PATH}:${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/


# Create hadoop User
RUN groupadd -r hadoop \
    && useradd -rm -s /bin/bash -g hadoop hadoop \
    && mkdir /var/run/sshd


RUN chown -R hadoop /etc/ssh/sshd_config /etc/pam.d/sshd /etc/profile /var/run/sshd
# Change user
USER hadoop

RUN set -x \
    && curl -fSL "$HADOOP_URL" -o ~/hadoop.tar.gz 

RUN cd /home/hadoop && tar -xvf ~/hadoop.tar.gz -C ~/ \
    && mv hadoop-$HADOOP_VERSION hadoop \
    && rm ~/hadoop.tar.gz*  

RUN echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/" > /opt/hadoop/etc/hadoop/hadoop-env.sh

WORKDIR /home/hadoop/hadoop

# For starting the ssh
RUN echo 'hadoop:hdfsroot' | chpasswd \
    && sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]